return items.map(item => {
  const report = item.json.output || item.json;
  const alertTitle = item.json.alert?.title || "Security Alert";
  const severity = item.json.alert?.severity || "Unknown";
  
  // Choose an emoji based on severity
  const icon = severity >= 4 ? "🔴" : "🟠";

  const message = `
### ${icon} SOC Alert Handoff: ${alertTitle}
---
${report}

---
*Report generated by Qwen2.5:7b • [Open TheHive](http://172.16.218.12:9000)*
  `.trim();

  return {
    json: {
      text: message,
      username: "Qwen-SOC-Agent",
      icon_url: "https://n8n.io" // Or any robot icon URL
    }
  };
});
